<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
?>

<div class="header-wl header_compare_link">
    <a href="<?php $block->getBaseUrl() ?>/catalog/product_compare/" title="<?= $block->escapeHtml(__('Compare Products')) ?>">
        <i class="pe-7s-graph3"></i>
        <span class="label"><?= $block->escapeHtml(__('Compare Products')) ?></span>
    </a>
</div>
