<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
$partner = $block->getProfileDetail();
$shopUrl = $escaper->escapeHtml($partner['shop_url']);
$sellerId = $partner->getSellerId();
$sellerProductCount = $helper->getSellerProCount($sellerId);
?>
<?php $products = $block->getBestsellProducts(); ?>
<?php if (count($products)) { ?>
    <div class="wk-mp-profile-block wk-mp-products-recently-added">
        <div class="block block-account" style="text-align: center; margin: 20px 0 50px !important;">
            <div class="block-title mgs-brand-widget">
                <strong><?= $escaper->escapeHtml(__("Recently Added Products")) ?></strong>
            </div>
        </div>
        <?php
        $products = $block->getBestsellProducts();
        $_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        ?>
        <div class="page-products page-with-filter fieldset wk-mp-fieldset" <?php if ($products->count()) { echo 'style="padding: 0;"';}?>>
            <?php
            $_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
            ?>
            <div class="products wrapper grid products-grid">
                <?php $iterator = 1; ?>
                <ol class="products  list items product-items row row-col-lg-3">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($products as $_product): ?>
                        <?= /* @escapeNotVerified */($iterator++ == 1) ? '<li class="item product product-item-info product-item col-lg-3 col-md-3 col-sm-4 col-xs-6 ">' : '</li><li class="item product product-item-info product-item col-lg-3 col-md-3 col-sm-4 col-xs-6 ">' ?>
                        <div class="product-item-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            ?>
                            <div class="product-top">
                                <?php // Product Image ?>
                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1" style="height: auto;">
                                    <?= $productImage->toHtml(); ?>
                                </a>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <button class="action tocart btn-cart">
                                            <span>
                                                <span>
                                                    <?= $escaper->escapeHtml(__('View Detail'))?>
                                                </span>
                                            </span>
                                        </button>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h5 class="product name product-item-name">
                                    <a class="product-item-link"
                                    href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h5>
                            </div>
                        </div>
                        <?= ($iterator == count($products)+1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <div class="wk-mp-collection-view-btn">
            <a href="<?= $escaper->escapeUrl($helper->getRewriteUrl('marketplace/seller/collection/shop/'.$shopUrl));?>" title="<?= $escaper->escapeHtml(__('View Collection'))?>">
                <?= $escaper->escapeHtml(__('View All %1 Products', $sellerProductCount))?>
            </a>
        </div>
    </div>
<?php } ?>
<?= $block->getChildHtml()?>
